service: infracreation-29112023
frameworkVersion: '3'
configValidationMode: error
provider:
  name: aws
  deploymentMethod: direct
  region: ap-south-1
  deploymentPrefix: infracreation

resources:
  - ${file(./resources/s3bucket.yml)}
  - ${file(./resources/ec2.yml)}
  - ${file(./resources/ecr.yml)}
  - ${file(./resources/secret.yml)}
  - ${file(./resources/parameter.yml)}